# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0016e5d9fcd913ac89b7768b444589f65ccab45f7e138169b9cd79649ffe164b58f9cd9da3f93ae8948a8df8b0292a41fd6f587745b712e487d92d10702499d5

test:
  secret_key_base: a6cd465df291b48aef6099da2d4de2d55ecfe85a6b09181d16e16d4ef4a60c92ee9e06c372039aaf622b33ee736ee178b5a679ed97653989aea285da8f46532e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
